/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menu.inventory;

import java.awt.Dimension;
import java.awt.event.ActionListener;

/**
 *
 * @author CallPC-Speed
 */
public class CreateInventoryItem extends javax.swing.JPanel {

    /**
     * Creates new form CreateInventoryItem
     */
    
    private ActionListener act;
    
    public CreateInventoryItem(ActionListener act) {
        initComponents();
        this.setSize(new Dimension(Integer.MAX_VALUE, 70));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE, 70));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE, 70));
        
        if(act!=null){
            this.act=act;
        }
        
        sButton1.setFocusPainted(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sButton1 = new spiders_components.SButton();

        setBackground(new java.awt.Color(153, 255, 153));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(237, 100));

        sButton1.setBorder(null);
        sButton1.setForeground(new java.awt.Color(255, 255, 255));
        sButton1.setBorderColor(new java.awt.Color(102, 102, 255));
        sButton1.setColor(new java.awt.Color(102, 102, 255));
        sButton1.setColorClick(new java.awt.Color(153, 153, 255));
        sButton1.setColorOver(new java.awt.Color(153, 153, 255));
        sButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        sButton1.setLabel("Create Inventory");
        sButton1.setRadius(30);
        sButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sButton1MousePressed(evt);
            }
        });
        sButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(sButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(sButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sButton1ActionPerformed

    private void sButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sButton1MousePressed
         if(act!=null){
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_sButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private spiders_components.SButton sButton1;
    // End of variables declaration//GEN-END:variables
}
